name: GitHub Actions

on:
  push:
    branches: ["main"]
    paths: [".github/workflows/**"]
  pull_request:
    branches: ["main"]
    paths: [".github/workflows/**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      # https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
      - name: Run actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash
