name: Ruby

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: ruby/setup-ruby@v1.187.0
        with:
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rake rubocop
